import os
import uuid
from PIL import Image
from .base_agent import BaseAgent

class EditorAgent(BaseAgent):
    def __init__(self):
        super().__init__()
        self.model_id = 'imagen-3.0-generate-001' 

    async def process(self, image: Image.Image, prompt: str) -> dict:
        return await self.process_effect(image, prompt)

    async def process_effect(self, image: Image.Image, prompt_or_type: str) -> dict:
        """
        Applies a real-time effect to the image using Imagen.
        """
        if not self.client:
            return {"error": "Client not initialized"}

        # Define prompts for special effects
        effect_prompts = {
            "no effect": None,
            "steam": "Add realistic enhanced steam and hot air rising from the food.",
            "fresh": "Enhance colors and add a fresh-food simulation with subtle water droplets and vibrant textures.",
            "glow": "Add a soft cinematic glow to the subject.",
            "product": "Enhance product details, sharpen branding, and clean up the background lighting."
        }

        # If it's a known type, use the preset prompt, otherwise use it as a custom prompt
        final_prompt = effect_prompts.get(prompt_or_type.lower(), prompt_or_type)
        
        if not final_prompt:
             return {"effect_type": prompt_or_type, "status": "none", "overlay_url": ""}

        try:
            print(f"DEBUG: EditorAgent generating image with prompt: {final_prompt}")
            response = self.client.models.generate_images(
                model=self.model_id,
                prompt=final_prompt,
                config={
                    'number_of_images': 1,
                    'include_rai_reason': True,
                }
            )

            if response.generated_images:
                print(f"DEBUG: EditorAgent successfully generated image.")
                generated_image = response.generated_images[0].image
                
                # Save to static directory
                filename = f"effect_{uuid.uuid4().hex}.png"
                static_path = os.path.join("static", "effects", filename)
                os.makedirs(os.path.dirname(static_path), exist_ok=True)
                
                generated_image.save(static_path)
                
                # Return the URL (backend is on port 8000)
                # We use a relative path /static/... which the frontend should handle
                # Or we can provide a fully qualified URL if we know the host
                return {
                    "effect_type": prompt_or_type,
                    "status": "applied",
                    "overlay_url": f"/static/effects/{filename}"
                }
            else:
                return {"error": "No image generated by Imagen"}

        except Exception as e:
            print(f"Imagen Error: {e}")
            return {"error": str(e)}
